spring:
  application:
    name: TaskFlow
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  config:
    import:
      - optional:file:./config/jwt-config.yaml


server:
  port: 8080