spring:
  application:
    name: TaskFlow
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

